name: Update Discourse Topic
description: "Automatically updates contents of a Discourse topic with the contents of a file in the repository."

inputs:
  file:
    description: "The file with Markdown to replace the Discourse topic with."
    required: true
  discourse_api_key:
    description: 'Discourse API key'
    required: true
  discourse_api_user:
    description: 'Discourse API username'
    required: true
  discourse_topic_id:
    description: 'Discourse topic ID'
    required: true
  discourse_api_url:
    description: 'Discourse API URL'
    required: true

runs:
  using: "composite"

  steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y jq gawk
      shell: bash

    - name: Read and transform repository file.
      id: read-and-fix
      run: |
        ./scripts/fix_links.sh .dtua/links.env ${{ inputs.file }} > tmp.md
        echo "README_JSON=$(jq -Rs . tmp.md)" >> $GITHUB_ENV
      shell: bash

    - name: Get first post ID from topic (and verify it's the first)
      id: get_post

      run: |
        response=$(curl -s "${{ inputs.discourse_api_url }}/t/${{ inputs.discourse_topic_id }}/posts.json" \
          -H "Api-Key: ${{ inputs.discourse_api_key }}" \
          -H "Api-Username: ${{ inputs.discourse_api_user }}")

        post=$(echo "$response" | jq '.post_stream.posts[0]')
        post_id=$(echo "$post" | jq '.id')
        post_number=$(echo "$post" | jq '.post_number')

        echo "First Post ID: $post_id"
        echo "Post Number: $post_number"

        if [ "$post_number" != "1" ]; then
          echo "❌ Error: This is not the first post in the topic. Aborting."
          exit 1
        fi

        echo "POST_ID=$post_id" >> $GITHUB_ENV
      shell: bash

    - name: Update Discourse post
      env:
        POST_ID: ${{ env.POST_ID }}
        README_JSON: ${{ env.README_JSON }}
      run: |
        echo "✅ Updating post ID: $POST_ID"

        curl -X PUT "${{ inputs.discourse_api_url }}/posts/${POST_ID}.json" \
          -H "Content-Type: application/json" \
          -H "Api-Key: ${{ inputs.discourse_api_key }}" \
          -H "Api-Username: ${{ inputs.discourse_api_user }}" \
          -d "{\"post\": {\"raw\": $README_JSON}}"

        echo "✅ Update complete."
      shell: bash